# Generated by Django 5.0.4 on 2024-04-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата платежа'),
        ),
    ]
