# Generated by Django 5.0.4 on 2024-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Перевод')], max_length=150, verbose_name='Вариант оплаты'),
        ),
    ]
