# Generated by Django 5.0.4 on 2024-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на сессию"),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Айди сессии"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Сумма оплаты"),
        ),
    ]
